### PR TITLE
The original code of dbt-Trino on Stackable

### PR DESCRIPTION
**Pull request by vafridman**
As we discussed with Lars, here is the code of the dbt-Trino on Stackable project for the copyright reasons.

### CODE REVIEW

**Comment by lfrancke** [comment]
Thank you very much!

**Review by lfrancke — COMMENTED** [review]
I haven't checked yet myself. Is logs/dbt.log needed or is that an accidental commit?
If it is accidental it'd be great if you could remove it from the git history.

**Comment by vafridman** [comment]
> I haven't checked yet myself. Is logs/dbt.log needed or is that an accidental commit? If it is accidental it'd be great if you could remove it from the git history.

My bad! I'll fix it.

**Review by lfrancke — APPROVED** [review]

**Comment by lfrancke** [comment]
Thank you very much for the contribution!

**Pull request merged**
